- README.md
Seems that ``PrismicDocument`` won't currently have property ``uid``, but there's ``id`` instead.
> Fix README: Use id instead of uid in example query

- package.json
As documented on npm's [page](https://www.npmjs.com/package/crypto) for the `crypto` package, this package is deprecated as there is now a Node-native library. The native library happens to be API compatible (at least for the purposes of `gatsby-source-prismic` anyway) so the dependency simply had to be removed from `package.json`.
> Remove depency on deprecated package 'crypto'.

- src/gatsby-node.js
When checking if a value is a DocumentLinkField, a tyepof on a null value will return 'object', which makes it pass the first test. This adds an additional check on value
> Fixes errors on null values

- src/normalize.js
Return undefined if a document link is broken.
> Return undefined for broken Document links

- src/fetch.js
- src/gatsby-node.js
Adds the ability to specify a general-purpose array of
fetchLinks options (see https://prismic.io/docs/javascript/query-the-api/fetch-linked-document-fields)
that allows deeper access to data for linked documents.
in gatsby-config.js
```
...
{
resolve: 'gatsby-source-prismic',
options: {
apiEndpoint: 'https://site.prismic.io/api/v2',
repositoryName: '...',
accessToken: '...',
htmlSerializer: ({ node, key, value }) => {...},
linkResolver: ({ node, key, value }) => {...},
fetchLinks: [
'article.topic',
'course.module'
]
}
}
...
```
in the linkResolver:
```
function linkResolver (doc) {
if (doc.type === 'article') {
console.log(doc.data.topic.value)
return `/${doc.data.topic.value.document.slug}/${doc.uid}/`
// ^ now this works! It wasn't possible to access anything passed data before,
// so …
```
> fetchLinks support in options

- README.md
- package.json
- src/gatsby-node.js
- src/normalize.js
- yarn.lock
Gatsby's filesystem source plugin was outdated, so I updated it and modified the code to properly work with v2.
> Migrate to Gatsby v2 (upgrade gatsby-source-filesystem, rename boundActionCreators)

- src/normalize.js
Fixes #54, which removes all of the following warnings that appear when running `gatsby develop`:
```
Calling "touchNode" with a nodeId is deprecated. Please pass an object containing a nodeId instead: touchNode({ nodeId: 'a-node-id' })
```
> Fix issue with touchNode warning

- src/fetch.js
- src/gatsby-node.js
In order to make it easier to deploy a Gatsby / Prismic site in a certain language per domain (eg .de, .nl, .com etc) I added an option to set the default Prismic content language. The default language is still *.
> Added language to plugin options to globaly set Prismic content language

- src/normalize.js
Since few days Prismic API started to give images URL with an encoded character (`%2F`), for example `https://satispay-website.cdn.prismic.io/satispay-website%2Fc359fb8c-88d3-45ec-9018-1abcf5e53869_kpi-04.svg`, giving problems with the Gatsby cache.
This fix simply decodes the URL bringing it to its original state, for example: `https://satispay-website.cdn.prismic.io/satispay-website/c359fb8c-88d3-45ec-9018-1abcf5e53869_kpi-04.svg`.
> Decode Prismic images URL

- src/gatsby-node.js
- src/normalize.js
When working with Prismic repos that have large media libraries, booting can sometimes take upwards of ten minutes or more, depending on your internet connection. This is due to the process of normalizing images during boot, in which case images are downloaded to the cache for use with gatsby-image-sharp and anything else that lets your process images.
Because this process can take a very long time, and there's no feedback when this is happening, this sometimes makes it seem like it gets stuck on the `source and transform nodes` part of booting the project. While this is happening, in one of the projects I'm working on, it downloads what seems like GBs of image data.
In cases where no local image processing is taking place, this option allows you to turn off normalization and local access …
> Ability to make the normalization of images optional

- docs/previews.md
- src/__tests__/hooks.js
- src/hooks.js
`mergePrismicPreviewData` will now throw if both `staticData` and `previewData` are undefined, but will otherwise return the other corresponding object if one of the two are falsey.
This change allows for cleaner composition of previews on unpublished documents from Prismic.
> fix: falsey staticData returns previewData, throws on both falsey

- src/fetchAllDocuments.js
Hi,
A quick fix of a typo causing only the first page to be fetched from Prismic.
Thanks!
> fix: fix only first page being fetched

- src/browser/normalizers.js
It was tough to track down but we have like 70 or so pages right now and randomly our previews stopped working. I finally figured out that when docs are deleted in Prismic its up to the content author to clean up any links associated to that doc. Prismic just puts the `type: 'broken_type'` on the document. Currently the `normlizeLinkField` method returns a null document if anything is wrong, my solution keeps with that functionality. 
#137
> Fix previews mysteriously failing to redirect

- src/__tests__/browser/normalizers.js
- src/__tests__/common/documentToNodes.js
- src/__tests__/node/generateTypeDefsForCustomType.js
- src/common/documentToNodes.js
- src/common/standardTypes.graphql
- src/node/generateTypeDefsForCustomType.js
Adds `alternate_languages` as a field on all Prismic documents. `alternate_languages` is of type `[PrismicLinkType!]!` which allows querying the document directly.
The following example demonstrates:
```graphql
query {
allPrismicPage {
nodes {
uid
alternate_languages {
... on PrismicPage {
uid
data {
title {
text
}
}
}
} 
}
}
}
```
> feat: add alternate language support

- README.md
This PR corrects an error in the README. The README referenced the linkResolver function being defined in `gatsby-node.js` when it is defined in `gatsby-config.js`.
> Correct gatsby-node.js to gatsby-config.js

- README.md
- src/api.ts
- src/types.ts
- src/usePrismicPreview.ts
- src/validateOptions.ts
- test/__snapshots__/gatsby-node.test.ts.snap
- test/__snapshots__/usePrismicPreview.test.ts.snap
This brings a new feature: to be able to build statically your website using a prismic release.
From prismic doc:
> A release allows your team to gather a collection of changes for a future version of your whole repository. The release can then publish all the changes to all the collected documents all at the same time.
I've added a README section to hint on how to use release. The only way to get a `releaseID` currently is by using the REST API, as explained in the README.
We plan to add a more convenient way to get the release ID, by adding it in the prismic API browser, which is accessible from the editor. This way it would be simple to copy/paste it.
> Add `releaseID` option

- docs/previews.md
Actually I tested the new HOC and they are working fine but only if I wrap with the `PreviewStoreProvider` in `gatsby-browser.js`. Doing it only in `gatsby-ssr.js` was not enough in my case.
> Fix preview documentation for wrapRootElement

- jest.config.js
- jest.setup.js
- package.json
- src/documentsToNodes.ts
- src/gatsby-browser.ts
- src/gatsby-node.ts
- src/gatsby-ssr.ts
- src/gqlTypes.ts
- src/mergePrismicPreviewData.ts
- src/schemasToTypeDefs.ts
- src/types.ts
- src/usePreviewStore.tsx
- src/validateOptions.ts
- src/withPreview.tsx
- src/withUnpublishedPreview.tsx
- test/__fixtures__/pageData.ts
- test/__snapshots__/gatsby-node.test.ts.snap
- test/__snapshots__/usePrismicPreview.test.ts.snap
- test/gatsby-node.test.ts
- test/gatsby-ssr.test.ts
- test/mergePrismicPreviewData.test.ts
- test/withPreview.test.tsx
- test/withPreviewResolver.test.tsx
- test/withUnpublishedPreview.test.tsx
- yarn.lock
See #246 for more details on why this change is needed and how it works.
This adds an option to `mergePrismicPreviewData` to decide which merge strategy to use. This change coincides with the decision to enforce the traverse strategy for all previews.
> feat: add _previewable field to mark previewable data

- src/gatsby-node.ts
- src/gqlTypes.ts
- test/__snapshots__/gatsby-node.test.ts.snap
The new `gatsby-plugin-imgix` types were being used without passing them to Gatsby's `createTypes` Node API. Now that it is passed to `createTypes`, the GraphQL system knows the type even if none of the repository's schemas contain an image field.
Fixes #238
> fix: support repositories without image fields

- docs/previews.md
I believe the exported page should be `NotFoundPage` rather than `PreviewPage` which is not in the scope.
> fix: Preview docs, unpublished code example

- src/gqlTypes.ts
- test/__snapshots__/gatsby-node.test.ts.snap
#286 
video_id seems to be vimeo specific field, this may confuse users who youtube or an other video source and the field would be null.
> fix: add video_id to oembed for issue #286

- packages/gatsby-plugin-prismic-previews/docs/api-withPrismicPreview.md
- packages/gatsby-plugin-prismic-previews/src/fieldProxies/documentDataFieldProxy.ts
- packages/gatsby-plugin-prismic-previews/src/lib/defaultFieldTransformer.ts
- packages/gatsby-plugin-prismic-previews/src/lib/mapRecordIndices.ts
- packages/gatsby-plugin-prismic-previews/src/lib/proxyDocumentSubtree.ts
- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewBootstrap.ts
- packages/gatsby-plugin-prismic-previews/test/usePrismicPreviewBootstrap-field-proxies.test.ts
- packages/gatsby-source-prismic/README.md
- packages/gatsby-source-prismic/package.json
- packages/gatsby-source-prismic/src/lib/buildFieldConfigMap.ts
- packages/gatsby-source-prismic/src/lib/mapRecordIndices.ts
- packages/gatsby-source-prismic/src/lib/mapRecordIndicies.ts
- packages/gatsby-source-prismic/src/plugin-options-schema.ts
- packages/gatsby-source-prismic/src/types.ts
- packages/gatsby-source-prismic/test/__testutils__/createPluginOptions.ts
- packages/gatsby-source-prismic/test/create-schema-customization.test.ts
- packages/gatsby-source-prismic/test/plugin-options-schema.test.ts
Adds ability to transform a custom type's field name before being processed. This is necessary to support invalid GraphQL field names, such as those with dashes (e.g. `my-field`).
The default value for `transformFieldName` will convert dashes to underscores (e.g. `my-field` will be converted to `my_field`). Users can override this default by providing a custom function.
**gatsby-source-prismic**
- Adds `transformFieldName` plugin options
**gatsby-plugin-prismic-previews**
- Adds `transformFieldName` config option to `withPrismicPreview()` HOC
> feat: transformFieldName option to support dashes in field names

- README.md
gatsbyjs.com only supports lowercase anchor links, while GitHub supports both lowercase and source version (e.g. "How-to-Use" vs "how-to-use").
Links to other documentation page have also been updated to link directly to GitHub. gatsbyjs.com would go to a 404 page since the URLs are not rewritten to use the repo base URL.
> docs: fix broken links to support gatsbyjs.com

- packages/gatsby-source-prismic/README.md
- packages/gatsby-source-prismic/src/constants.ts
- packages/gatsby-source-prismic/src/plugin-options-schema.ts
- packages/gatsby-source-prismic/src/types.ts
- packages/gatsby-source-prismic/test/__testutils__/createAPIRepositoryMockedRequest.ts
- packages/gatsby-source-prismic/test/__testutils__/createCustomTypesAPICustomType.ts
- packages/gatsby-source-prismic/test/__testutils__/createCustomTypesAPIMockedRequest.ts
- packages/gatsby-source-prismic/test/__testutils__/createPluginOptions.ts
- packages/gatsby-source-prismic/test/plugin-options-schema.test.ts
- packages/gatsby-source-prismic/test/source-nodes.test.ts
- packages/test-site/.env.secret.example
- packages/test-site/.gitignore
- packages/test-site/gatsby-config.js
Related Issue: #349
Related PR: #316 
Adds a `customTypesApiToken` plugin option to `gatsby-source-prismic` that enables automatic custom type schema fetching.
This can replace the practice of users needing to manually copy and paste custom type JSON schemas into their project and passing them via the `schemas` option.
This feature relies on the **BETA** Custom Types API that must be enabled on a per-repository basis.
**See**: https://prismic.io/docs/technologies/custom-types-api
If the schemas pulled from the API need to be overridden, they can still be provided via the `schemas` option. Schemas pulled from the API and provided manually in `gatsby-node.js` will be merged, with priority given to the manual schemas. This should help in the future with Slice Machine integration and local …
> feat: add automatic schema fetching with Custom Types API

- packages/gatsby-source-prismic/README.md
- packages/gatsby-source-prismic/src/constants.ts
- packages/gatsby-source-prismic/src/plugin-options-schema.ts
- packages/gatsby-source-prismic/src/types.ts
- packages/gatsby-source-prismic/test/__testutils__/createCustomTypesAPIMockedRequest.ts
- packages/gatsby-source-prismic/test/plugin-options-schema.test.ts
Adds the ability to configure the Custom Types API endpoint. It will continue to default to `https://customtypes.prismic.io/customtypes`.
Implemented per @MarcMcIntosh's review (#349).
> feat: add customTypesApiEndpoint option

- packages/gatsby-source-prismic/package.json
- packages/gatsby-source-prismic/src/builders/buildImageBaseFieldConfigMap.ts
- packages/gatsby-source-prismic/src/builders/buildImgixImageTypes.ts
- packages/gatsby-source-prismic/src/create-schema-customization.ts
- yarn.lock
Hey there Prismic (and @angeloashmore) 👋 
This PR is the start of the process to migrating the Prismic Imgix GraphQL field types over to use @imgix/gatsby internally. A significant benefit of doing this is that the new Gatsby image plugin, gatsby-plugin-image, is supported out of the box.
This PR is not “finished”, but I believe it is in a working state. I’m opening this at an early stage to ensure that I’m going down a path that Prismic is happy with (i.e. in terms of the code) and to get feedback on ways that I could architect the code differently, if the target branch is correct, or if there is any more work to be done (e.g. tests?). @angeloashmore I still have your message about the potential issue you raised on Slack saved, and I’m looking to investigate that this week.
Feel free to …
> feat: use @imgix/gatsby field helpers and support new gatsby-plugin-image v3 API

- packages/gatsby-plugin-prismic-previews/src/fieldProxies/alternativeLanguagesFieldProxy.ts
- packages/gatsby-plugin-prismic-previews/src/fieldProxies/documentFieldProxy.ts
- packages/gatsby-plugin-prismic-previews/test/__testutils__/createPrismicAPIDocument.ts
- packages/gatsby-plugin-prismic-previews/test/useMergePrismicPreviewData.test.ts
- packages/gatsby-plugin-prismic-previews/test/usePrismicPreviewBootstrap-field-proxies.test.ts
- packages/gatsby-source-prismic/src/builders/buildAlternateLanguageType.ts
- packages/gatsby-source-prismic/src/create-schema-customization.ts
- packages/gatsby-source-prismic/src/lib/createCustomType.ts
- packages/gatsby-source-prismic/src/types.ts
- packages/gatsby-source-prismic/test/__testutils__/createPrismicAPIDocument.ts
- packages/gatsby-source-prismic/test/create-schema-customization-alternate-languages.test.ts
- packages/gatsby-source-prismic/test/create-schema-customization-document.test.ts
- packages/test-site/gatsby-config.js
- packages/test-site/src/linkResolver.js
- packages/test-site/src/linkResolver.ts
- packages/test-site/src/pages/index.tsx
> feat: restore alternate_language document field

- packages/gatsby-plugin-prismic-previews/package.json
- packages/gatsby-plugin-prismic-previews/src/fieldProxies/imageFieldProxy.ts
- packages/gatsby-plugin-prismic-previews/test/usePrismicPreviewBootstrap-field-proxies.test.ts
- packages/gatsby-source-prismic/package.json
- packages/gatsby-source-prismic/src/builders/buildImageBaseFieldConfigMap.ts
- packages/gatsby-source-prismic/test/create-schema-customization-image.test.ts
- tsconfig.json
- yarn.lock
Ensures existing Imgix URL parameters on image URLs are retained after `gatsby-image` and `gatsby-plugin-image` transformations.
Currently blocked by an issue described in this comment: https://github.com/imgix/gatsby/issues/122#issuecomment-846256825
> fix: retain existing Imgix URL parameters on images

- packages/gatsby-plugin-prismic-previews/docs/migrating-from-gatsby-source-prismic.md
Looks like there was a type. The new function was not being used in the updated code example.
> Updated incorrect call to withUnpublishedPreview

- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewBootstrap.ts
- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewResolver.ts
- packages/gatsby-source-prismic/src/lib/normalizeDocumentSubtree.ts
- packages/gatsby-source-prismic/src/lib/sourceNodesForDocumentIds.ts
- packages/gatsby-source-prismic/test/__fixtures__/kitchenSinkSchema.json
- packages/gatsby-source-prismic/test/create-schema-customization.test.ts
- packages/gatsby-source-prismic/test/source-nodes.test.ts
- test-site/schemas/kitchen_sink.json
- test-site/src/pages/{PrismicPrefixKitchenSink.uid}.tsx
- fix(source): correctly resolve fields with transformed names
- fix(previews): prevent bootstrapping or resolving more than once
Fields with transformed names using the `transformFieldName` plugin option were not resolved correctly. Rather than return the field value, `null` was returned.
🐋
> fix: correctly resolve fields with transformed names

- packages/gatsby-plugin-prismic-previews/package.json
- packages/gatsby-plugin-prismic-previews/src/plugin-options-schema.ts
- packages/gatsby-plugin-prismic-previews/src/types.ts
- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewBootstrap.ts
- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewResolver.ts
- packages/gatsby-plugin-prismic-previews/test/__testutils__/createPluginOptions.ts
- packages/gatsby-plugin-prismic-previews/test/usePrismicPreviewBootstrap-field-proxies.test.ts
- packages/gatsby-source-prismic/package.json
- packages/gatsby-source-prismic/src/buildDependencies.ts
- packages/gatsby-source-prismic/src/lib/queryAllDocuments.ts
- packages/gatsby-source-prismic/src/lib/queryDocumentsByIds.ts
- packages/gatsby-source-prismic/src/plugin-options-schema.ts
- packages/gatsby-source-prismic/src/types.ts
- packages/gatsby-source-prismic/test/__testutils__/createPluginOptions.ts
- yarn.lock
Adds a `pageSize` plugin option to `gatsby-source-prismic` and `gatsby-plugin-prismic-previews` which allows setting the `pageSize` option to `@prismicio/client`.
This allows a user to reduce API payloads during node sourcing by setting the page size to less than the maximum (100). This may be necessary if the Prismic REST API fails the request due to result that is larger than the maximum payload size.
> feat: add `pageSize` option

- packages/gatsby-source-prismic/src/builders/buildImageBaseFieldConfigMap.ts
- packages/gatsby-source-prismic/src/lib/createRemoteFileNode.ts
- packages/gatsby-source-prismic/test/source-nodes-image.test.ts
Data from Image and Link to Media fields can be downloaded locally and accessed via `localFile`. The downloaded file and its `File` node are cached.
Before this PR, the `File` node could sometimes be garbage collected, resulting in a `null` value for `localFile`. This PR ensures `File` node are not garbage collected by using the `touchNode` action.
Resolves: #471
🦕
> fix: ensure cached localFile fields are not null

- packages/gatsby-source-prismic/src/buildDependencies.ts
- packages/gatsby-source-prismic/src/builders/buildStructuredTextType.ts
- packages/gatsby-source-prismic/src/lib/buildScalarType.ts
- packages/gatsby-source-prismic/src/runtime/normalizers/image.ts
- packages/gatsby-source-prismic/src/types.ts
- packages/gatsby-source-prismic/test/__testutils__/createGatsbyContext.ts
- packages/gatsby-source-prismic/test/create-schema-customization-structured-text.test.ts
- yarn.lock
This PR changes the GraphQL type of the `richText` and `raw` fields from Rich Text and Title fields. It replaces the current JSON scalar to a custom PrismicStructuredText scalar. PrismicStructuredText acts the same as JSON but with a custom name.
Using a custom scalar helps when using tools like GraphQL Code Generator to generate TypeScript types. This will allow setting a custom TypeScript type for the field.
Example partial GraphQL Code Generator config:
```yaml
generates:
./src/types.generated.ts:
plugins:
- typescript
- typescript-operations
config:
skipTypename: true
avoidOptionals: true
scalars:
PrismicStructuredText: import('@prismicio/types').RichTextField
```
> feat: type Rich Text and Title fields with custom PrismicStructuredText scalar

- packages/gatsby-plugin-prismic-previews/src/plugin-options-schema.ts
- packages/gatsby-plugin-prismic-previews/src/types.ts
- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewBootstrap.ts
- packages/gatsby-plugin-prismic-previews/src/usePrismicPreviewResolver.ts
- packages/gatsby-source-prismic/src/buildDependencies.ts
- packages/gatsby-source-prismic/src/plugin-options-schema.ts
- packages/gatsby-source-prismic/src/types.ts
This PR adds support for Route Resolvers via the `routes` option. To learn more about Route Resolver and how it compares to Link Resolver, see: https://prismic.io/docs/core-concepts/link-resolver-route-resolver
Note that if a `routes` option is given to `gatsby-source-prismic`, it should also be added to `gatsby-plugin-prismic-previews`. The option can be given to both plugins in exactly the same way.
Example `gatsby-config.js` with Route Resolvers:
```javascript
module.exports = {
plugins: [
{
resolve: "gatsby-source-prismic",
options: {
repositoryName: "repo-name",
routes: [
{
type: "page",
path: "/:lang/:uid",
},
{
type: "blog_post",
path: "/:lang/blog/:category?/:uid",
resolvers: {
country: "country",
category: "country.category",
},
},
],
},
},
],
};
```
🐳
> feat: add `routes` option to support Route Resolver

- packages/gatsby-source-prismic/src/lib/buildFieldConfigMap.ts
- packages/gatsby-source-prismic/src/lib/toFieldConfig.ts
- packages/gatsby-source-prismic/test/create-schema-customization-slices.test.ts
> fix(source): exclude empty Slice Zones in GraphQL type

- packages/gatsby-source-prismic/src/runtime/typePaths.ts
Fixes #490
This adds support for Shared Slice models without `primary` or `items` models. This should be invalid, but it is possible to push and pull models to the Custom Types API without these fields.
🦙
> fix: support Shared Slices without primary/items models

- packages/gatsby-source-prismic/src/constants.ts
- packages/gatsby-source-prismic/test/runtime-image.test.ts
- packages/gatsby-source-prismic/test/runtime.test.ts
This PR removes the default `q=50` Imgix URL parameter added to all images by `gatsby-source-prismic` and, by extension, `gatsby-plugin-prismic-previews`.
For more details on why this was changed, see: #498
Thanks to @jodiedoubleday for reporting this.
🐈
> fix: remove default `q=50` Imgix parameter for Gatsby images

- packages/gatsby-plugin-prismic-previews/src/components/Modal.tsx
This PR fixes an issue where the scroll position of the app is not the top of the page after a preview has gone through the bootstrap process. This would be seen at the start of a preview session (i.e. after the preview resolve page) or after refreshing an existing preview session.
This was due to `@reach/dialog`'s automatic focus trapping. Because the dialog is not positioned at the top of the page and includes a button which automatically gains focus, the scroll position was changed.
This PR removes the focus trapping capabilities of `@reach/dialog`.
(credit to @asyarb for reporting the issue and helping to find the fix)
> fix(previews): retain correct scroll position during preview bootstrapping

- packages/gatsby-source-prismic/src/lib/normalizeDocumentSubtree.ts
We noticed our shared slice were not properly rendered in the graphQL explorer.
It seems the test to check wether a value was a SharedSlice is wrong as it tests if it's an array of value
> fix: normalize Shared Slices using a corrected refinement

- packages/gatsby-plugin-prismic-previews/src/constants.ts
- packages/gatsby-plugin-prismic-previews/src/lib/buildTypePathsStoreFilename.ts
- packages/gatsby-plugin-prismic-previews/src/on-post-bootstrap.ts
- packages/gatsby-plugin-prismic-previews/test/__testutils__/createTypePathsMockedRequest.ts
- packages/gatsby-plugin-prismic-previews/test/on-post-bootstrap.test.ts
- packages/gatsby-plugin-prismic-previews/test/useMergePrismicPreviewData.test.ts
- packages/gatsby-plugin-prismic-previews/test/usePrismicPreviewBootstrap.test.ts
- packages/gatsby-plugin-prismic-previews/test/withPrismicPreview.test.tsx
- packages/gatsby-plugin-prismic-previews/test/withPrismicUnpublishedPreview.test.tsx
- packages/gatsby-source-prismic/package.json
- packages/gatsby-source-prismic/src/runtime/runtime.ts
- packages/gatsby-source-prismic/src/runtime/serializePath.ts
- packages/gatsby-source-prismic/test/__testutils__/createPluginOptions.ts
- packages/gatsby-source-prismic/test/__testutils__/createPrismicAPIDocument.ts
- packages/gatsby-source-prismic/test/__testutils__/md5.ts
- packages/gatsby-source-prismic/types/tiny-hashes.d.ts
- yarn.lock
This PR improves performance during previews orchistrated by `gatsby-plugin-prismic-previews`. The performance improvement is negligible for relatively small repositories, but should be noticable to large repositories (>500 documents).
Note that this does not fundamentally change the way previews work; it will still fetch all documents in the repository to ensure near identical behavior to the Gatsby's native GraphQL API.
The changes in this PR remove extra computation that is not critical during client-side previews.
For more details, see #500.
(Thank you to @Baztoune for diagnosing the issue and finding a fix. Also, thank you to everyone who has reported the issue in #500 and shared their experience.)
> refactor(previews): improve performance for large repositories

- packages/gatsby-plugin-prismic-previews/package.json
This PR adds support for React 18 in `gatsby-plugin-prismic-previews`.
No functional changes were required, just a `peerDependency` update.
Fixes #507
> fix(previews): support React 18

- packages/gatsby-source-prismic/src/lib/toFieldConfig.ts
- packages/gatsby-source-prismic/src/runtime/typePaths.ts
This PR fixes a bug where Gatsby's `createSchemaCustomization` step would throw if a Custom Type's Slice Zone was missing a `choices` property. This can happen if a Slice Zone is enabled, but no Slices are added.
Note that bug is different than `{ choices: {} }`, which was fixed in [`v5.2.4`](https://github.com/prismicio/prismic-gatsby/commit/23cb1316dd081249ec1788c6963eeba0a3e2c077).
(Thanks to @a-trost for reporting the bug!)
> fix(source): support Slice Zones with missing `choices` property

- src/api.ts
- src/types.ts
This PR backports the `pageSize` plugin option from v4+ to v3.
The `pageSize` plugin option is described as such in the `gatsby-source-prismic` v5 documentation:
> Set the maximum page size used when fetching documents from the Prismic API. If you are reaching API limits due to large documents, set this to a number less than the maximum (100). By default, the maximum page size of 100 is used.
Setting `pageSize` to a value less than the maximum (100) is necessary in cases where the query response exceeds Prismic's Rest API maximum payload size.
> feat(v3): add `pageSize` plugin option

- CHANGELOG.md
- lerna.json
- packages/gatsby-plugin-prismic-previews/CHANGELOG.md
- packages/gatsby-plugin-prismic-previews/package.json
- packages/gatsby-source-prismic/CHANGELOG.md
- packages/gatsby-source-prismic/package.json
- yarn.lock
This PR updates `@imgix/gatsby` to the latest version. Updating the package fixes a bug preventing Gatsby >= v5.10.0 projects from starting or building.
See #531 for more details.
> fix: update `@imgix/gatsby` to support Gatsby v5.10.0

- packages/gatsby-source-prismic/src/lib/normalizeDocument.ts
Current shared slices with repeated items will only return the first item. This causes GraphQL to error as it expects an Iterable but the data is returning an object.
> fix: return all repeated items of a SharedSlice, not just the first item
